#pragma once

#include_next <config.h>

#define BACKLIGHT_PWM_PERIOD 2000
#define BACKLIGHT_PWM_DRIVER PWMD1
#define BACKLIGHT_PWM_CHANNEL 1

#define MOUSE_EXTENDED_REPORT TRUE
#define POINTING_DEVICE_TASK_THROTTLE_MS 5
